server {
    listen 80;
    server_name _;
    default_type application/json;

    location = /lnurlp/e2e {
        alias /usr/share/nginx/html/pay-request.json;
    }

    # Source: https://github.com/lightning/bolts/blob/master/11-payment-encoding.md
    # This BOLT-11 test vector does not originate from DFX and cannot be paid.
    location = /cb {
        alias /usr/share/nginx/html/invoice.json;
    }

    location / {
        return 404;
    }
}
